### ISSUE TITLE
cur-add  show Error in workflow

### ISSUE THREAD

**Issue by touchmii** [tomy0000000/coon#3]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/14190567/63079457-f5a53c80-bf70-11e9-84b6-08a655ff5b26.png">

[15:27:03.812] Coon[Script Filter] Queuing argument '(null)'
[15:27:04.057] Coon[Script Filter] Script with argv '(null)' finished
[15:27:04.060] STDERR: Coon[Script Filter] .
15:27:03 workflow.py:2061 DEBUG    ---------- Coon (1.0.1) ----------
15:27:03 workflow.py:1468 DEBUG    reading settings from /Users/touchmii/Library/Application Support/Alfred/Workflow Data/tech.tomy.coon/settings.json
15:27:03 workflow.py:2343 DEBUG    update check not due
.
15:27:03 workflow.py:2061 DEBUG    ---------- Coon (1.0.1) ----------
15:27:03 workflow.py:2343 DEBUG    update check not due
15:27:03 query.py:72 INFO     Run Pattern 0
15:27:03 workflow.py:2080 ERROR    'favorites'
Traceback (most recent call last):
  File "/Users/touchmii/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.68471F7D-0269-4F81-9ACA-2336C025FF43/currency/workflow/workflow.py", line 2073, in run
    func(self)
  File "/Users/touchmii/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.68471F7D-0269-4F81-9ACA-2336C025FF43/currency/__init__.py", line 66, in convert
    query.run_pattern(workflow, rates)
  File "/Users/touchmii/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.68471F7D-0269-4F81-9ACA-2336C025FF43/currency/query.py", line 74, in run_pattern
    func(workflow, rates)
  File "/Users/touchmii/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.68471F7D-0269-4F81-9ACA-2336C025FF43/currency/query.py", line 82, in pattern_0
    for currency in settings["favorites"]:
KeyError: 'favorites'
15:27:03 workflow.py:2082 INFO     for assistance, see: https://git.io/fjD6M
15:27:03 workflow.py:2103 DEBUG    ---------- finished in 0.004s ----------
15:27:03 workflow.py:2254 DEBUG    set last run version: 1.0.1
15:27:03 workflow.py:2103 DEBUG    ---------- finished in 0.038s ----------
[15:27:04.064] Coon[Script Filter] {"items": [{"valid": false, "subtitle": "'favorites'", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'Coon'"}]}

**Comment by tomy0000000** [comment]
This error is identical to #1 
If you've installed v1.0.0 before,
try reinstall using the following steps:

1. type `cur worfklow:opendata`, a Finder window will be opened
2. delete `settings.json`
3. delete and reinstall v1.0.1 from the release

Close the issue if this helped,
and feel free to let me know if this doesn't work.
Thanks.😜
