### ISSUE TITLE
Error on all operation - " KeyError: 'favorites' "

### ISSUE THREAD

**Issue by vinaywadhwa** [tomy0000000/Coon#8]
Debug Logs - 

[15:46:04.778] Coon[Script Filter] Queuing argument 'USD'
[15:46:05.050] Coon[Script Filter] Script with argv 'USD' finished
[15:46:05.054] STDERR: Coon[Script Filter] .
15:46:04 workflow.py:2061 DEBUG    ---------- Coon (1.0.0) ----------
15:46:04 workflow.py:1468 DEBUG    reading settings from /Users/username/Library/Application Support/Alfred/Workflow Data/tech.tomy.coon/settings.json
15:46:04 workflow.py:2343 DEBUG    update check not due
.
15:46:04 workflow.py:2061 DEBUG    ---------- Coon (1.0.0) ----------
15:46:04 workflow.py:2343 DEBUG    update check not due
15:46:04 __init__.py:35 INFO     all
15:46:04 workflow.py:2080 ERROR    'favorites'
Traceback (most recent call last):
  File "/Users/username/GoogleDrive/alfred_prefs/Alfred.alfredpreferences/workflows/user.workflow.2E339F7D-6924-432A-BE53-A13E6B27ACFD/currency/workflow/workflow.py", line 2073, in run
    func(self)
  File "/Users/username/GoogleDrive/alfred_prefs/Alfred.alfredpreferences/workflows/user.workflow.2E339F7D-6924-432A-BE53-A13E6B27ACFD/currency/__init__.py", line 39, in load
    items = generate_items(query, currencies.keys(), workflow.settings["favorites"], True)
**KeyError: 'favorites'**
15:46:04 workflow.py:2082 INFO     for assistance, see: https://git.io/fjD6M
15:46:04 workflow.py:2103 DEBUG    ---------- finished in 0.005s ----------
15:46:04 workflow.py:2254 DEBUG    set last run version: 1.0.0
15:46:04 workflow.py:2103 DEBUG    ---------- finished in 0.042s ----------
[15:46:05.065] Coon[Script Filter] {"items": [{"valid": false, "subtitle": "'favorites'", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'Coon'"}]}

**Comment by vinaywadhwa** [comment]
just noticed this is solved.. Closing, sorry

**Comment by Bovey0809** [comment]
Same problem, how did you solve?

**Comment by tomy0000000** [comment]
Just for reference, this is a duplicate of #1 
@Bovey0809 updating to the latest version should solve the problem
If there's any further problem, please open another issue, thanks
